#!/usr/bin/env node
// Copies the shared Beta Studio system (components, fonts, audio, assets, frame.md)
// into every HyperFrames project under compositions/, templates/ and thumbnails/.
//
//   node tools/sync-system.mjs            # sync all projects
//   node tools/sync-system.mjs reel-01    # only projects whose folder name contains "reel-01"
//   node tools/sync-system.mjs --check    # exit 1 if any project is out of date
//
// Why copies and not "../" paths: HyperFrames serves each project with its own
// root as base URL and lints "../" asset paths as an error
// (invalid_parent_traversal_in_asset_path). Copies keep every project
// self-contained for preview, render, cloud render and the desktop app.
// The copies are git-ignored; this folder's sources are the single truth.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const CHECK = args.includes("--check");
const filter = args.find((a) => !a.startsWith("--"));

// source → destination (inside <project>/system/)
const MAP = [
  ["components/beta.css", "beta.css"],
  ["components/beta.js", "beta.js"],
  ["components/fonts.css", "fonts.css"],
  ["components/gsap.min.js", "gsap.min.js"],
  ["fonts", "fonts"],
  ["sound-effects", "sfx"],
  ["music", "music", (f) => /\.(mp3|m4a|wav|md|txt)$/i.test(f)],
  ["assets", "assets"],
];

function findProjects() {
  const out = [];
  for (const base of ["compositions", "templates", "thumbnails", "components"]) {
    const dir = join(ROOT, base);
    if (!existsSync(dir)) continue;
    const walk = (d, depth) => {
      if (existsSync(join(d, "hyperframes.json"))) return out.push(d);
      if (depth > 1) return;
      for (const e of readdirSync(d)) {
        const p = join(d, e);
        if (statSync(p).isDirectory() && !e.startsWith(".") && e !== "system" && e !== "node_modules") walk(p, depth + 1);
      }
    };
    walk(dir, 0);
  }
  return out.filter((p) => !filter || p.includes(filter));
}

function listFiles(src, pred) {
  const st = statSync(src);
  if (st.isFile()) return [""];
  const files = [];
  const walk = (d, rel) => {
    for (const e of readdirSync(d)) {
      const p = join(d, e);
      const r = rel ? `${rel}/${e}` : e;
      if (statSync(p).isDirectory()) walk(p, r);
      else if (!pred || pred(e)) files.push(r);
    }
  };
  walk(src, "");
  return files;
}

const hash = (p) => createHash("sha1").update(readFileSync(p)).digest("hex");

let stale = 0;
const projects = findProjects();
for (const proj of projects) {
  const sys = join(proj, "system");
  if (!CHECK) {
    rmSync(sys, { recursive: true, force: true });
    mkdirSync(sys, { recursive: true });
  }
  for (const [srcRel, dstRel, pred] of MAP) {
    const src = join(ROOT, srcRel);
    if (!existsSync(src)) continue;
    for (const f of listFiles(src, pred)) {
      const from = f ? join(src, f) : src;
      const to = f ? join(sys, dstRel, f) : join(sys, dstRel);
      if (CHECK) {
        if (!existsSync(to) || hash(from) !== hash(to)) {
          stale++;
          console.log(`stale: ${relative(ROOT, to)}`);
        }
      } else {
        mkdirSync(dirname(to), { recursive: true });
        cpSync(from, to);
      }
    }
  }
  // brand manifest: tells blocks whether the official logo file exists
  const logo = ["logo.svg", "logo.png", "logo.webp"].find((f) => existsSync(join(ROOT, "assets", f)));
  const brandJs = `/* generated by tools/sync-system.mjs */\nwindow.BS_BRAND = ${JSON.stringify({ logo: logo ? `system/assets/${logo}` : null })};\n`;
  if (CHECK) {
    const cur = existsSync(join(sys, "brand.js")) ? readFileSync(join(sys, "brand.js"), "utf8") : "";
    if (cur !== brandJs) stale++;
  } else {
    writeFileSync(join(sys, "brand.js"), brandJs);
  }
  // shared sub-composition blocks → <project>/compositions/<name>.html
  const blocks = join(ROOT, "components", "blocks");
  if (existsSync(blocks) && !proj.endsWith(join("components", "gallery"))) {
    for (const f of readdirSync(blocks).filter((x) => x.endsWith(".html"))) {
      const from = join(blocks, f);
      const to = join(proj, "compositions", f);
      if (CHECK) {
        if (!existsSync(to) || hash(from) !== hash(to)) {
          stale++;
          console.log(`stale: ${relative(ROOT, to)}`);
        }
      } else {
        mkdirSync(dirname(to), { recursive: true });
        cpSync(from, to);
      }
    }
  }
  // brand truth for HyperFrames (design spec precedence: frame.md first)
  const frameSrc = join(ROOT, "frame.md");
  const frameDst = join(proj, "frame.md");
  if (CHECK) {
    if (!existsSync(frameDst) || hash(frameSrc) !== hash(frameDst)) stale++;
  } else {
    writeFileSync(frameDst, readFileSync(frameSrc));
  }
  if (!CHECK) console.log(`synced  ${relative(ROOT, proj)}`);
}
if (CHECK) {
  console.log(stale ? `${stale} stale file(s) — run: npm run sync` : `all ${projects.length} project(s) in sync`);
  process.exit(stale ? 1 : 0);
}
