import React from "react";
import { Audio } from "@remotion/media";
import { staticFile, useVideoConfig } from "remotion";

export type SfxName = "click" | "key" | "swipe" | "whoosh" | "notify" | "confirm" | "ready" | "shimmer";

/** One sound effect from public/sfx (generated by scripts/make-sfx.py). */
export const Sfx: React.FC<{ name: SfxName; at: number; volume?: number }> = ({ name, at, volume = 1 }) => {
  const { fps } = useVideoConfig();
  return <Audio name={`sfx:${name}`} from={Math.max(0, at)} src={staticFile(`sfx/${name}.wav`)} volume={volume} premountFor={fps} />;
};
